name: Feature Request
description: Suggest a new feature or improvement for AI-DLC
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the form below.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: A clear description of the feature
    validations:
      required: true
  - type: dropdown
    id: phase
    attributes:
      label: Affected Phase
      description: Which phase of AI-DLC does this relate to?
      options:
        - INCEPTION
        - CONSTRUCTION
        - OPERATIONS
        - All Phases
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case or problem this feature would solve
      placeholder: When I try to... I want to be able to...
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Stage
        - New Agent
        - Enhancement
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
    validations:
      required: false
